version: 2.1
workspace-name: &working_directory /tmp/workspace
project-id-prod: &project-id-prod interstellar-prod-env
project-id-staging: &project-id-staging interstellar-staging-env
ruby_docker_image: &python_docker_image python:3.7-stretch

machine:
  timezone: Europe/Berlin

orbs:
  notify-slack: interstellar/notify-slack@0.1.18

jobs:

  build-and-upload-to-bucket: &upload-to-bucket
    docker:
      - image: *python_docker_image
    working_directory: *working_directory
    steps:
      - checkout
      - attach_workspace:
          at: *working_directory
      - run:
          name: Setup environment
          command: |
            apt-get update && apt-get install lsb-release -y
            export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            apt-get update
            apt-get install google-cloud-sdk -y
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_CLOUD_PROJECT}
            gcloud --quiet config set compute/zone europe-west3
      - run:
          name: Install dependencies
          command: pip install --upgrade setuptools && pip install -r requirements.txt
      - run:
          name: Build HTML documentation
          command: make html
      - run:
          name: Upload schemas to Google Cloud Storage Bucket
          command: gsutil rsync -r -d ./build/html/ gs://$BUCKET_NAME
      - notify-slack/deploy

  deploy-to-staging:
    environment:
      GOOGLE_CLOUD_PROJECT: *project-id-staging
      WORKING_DIRECTORY: *working_directory
      BUCKET_NAME: docs.staging.interstellar.earth
    <<: *upload-to-bucket

  deploy-to-prod:
    environment:
      GOOGLE_CLOUD_PROJECT: *project-id-prod
      WORKING_DIRECTORY: *working_directory
      BUCKET_NAME: docs.interstellar.earth
    <<: *upload-to-bucket

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-to-staging:
          context: gcp
      - hold:
          type: approval
          requires:
            - deploy-to-staging
          filters:
            branches:
              only: master
      - deploy-to-prod:
          requires:
            - hold
          context: gcp
          filters:
            branches:
              only: master